### ISSUE TITLE
Common Ruby variables names

### ISSUE THREAD

**Issue by jeromedalbert** [rubocop-hq/ruby-style-guide#181]
I have recently noticed thas this guide lacks a centralized list of common variable names that would help new Rubyists bootstrap quicker with more confidence. I am not sure if adding this would be a good idea though, maybe it is more a "what I feel right now" problem, or a general programming problem (though Ruby has its specificities).

Of course nothing beats naming a variable by its intention. The name should reveal what it does, how it is or will be used, why it exists, etc. For example a `d` class attribute does not say much, whereas `elapsed_days` is more understandable.

That being said, 1 letter names are ok if they are used for local variables inside short blocks/methods. More generally the length of a name corresponds to the size of its scope. Example : `i`, `j` and `k` are common conventions for indexes. `|e|` seems to be a common Ruby convention inside a short block, for any element.
Ruby code also seems to use shorter variable names than languages such as Java.

Here is what I have noticed In the guide :
- When using reduce, use `|a, e|`. I for one prefer `|acc, e|`. Anyway.
- When defining binary operators, name the argument `other`.

Here is what I have noticed in short blocks/methods (in the guide or in other source codes) : 
- any element : `e`. Maybe `elem` too ?
- array : `arr` or `ary` or `array`. Never seen `a`.
- hash : `h` or `hash`. Hask key : `k` or `key`. Hash value : `v` or `e`.  
  Example 1 : `h = Hash.new { |h, k| h[k] = ... }`  
  Example 2 : `hash.each { |k, v| ... }`
- String : `str`. Note sure if `s` is used a lot, and never seen any example with `string` so far.
- Symbol : Maybe `sym`.
- Number : `n`.
- Exception, Error, etc : `e`. Maybe `err` or `ex` too.
- Any object : `obj`. I think I have never seen `o` so far.
- Class : `klass`.
- File : `f` or `file`
- Loop index : `i`, `j`, `k`
- ... probably more

**Comment by EdvardM** [comment]
I noticed this was closed, but as `reek`, that is another good tool in addition to rubocop, but has a bit different goal -- it complains about uncommunicative names, and if I use the recommended `|a, e|` for inject then reek gets annoyed.

To quote discussion in https://github.com/troessner/reek/issues/35#issuecomment-198369853, I used the example

`array_of_integers.inject { |a, e| a + e }`

and I have te to agree with others, that here it's just too terse. `(1..10).map { |i| i*2 }` is just fine and any extra would.. um, just seem extra, but with inject it'd be much more readable to have

`array_of_integers.inject { |acc, e| acc + e }` or

`array_of_integers.inject { |acc, elt| acc + elt }` # borrowing Python community for generic element

or maybe the best, 

`array_of_integers.inject { |acc, it| acc + it }` which was tipped by mvz in that discussion.

adamstegman: I agree partly with what you said. `Hash#each { |k, v| .. }` is bad in a context, because like you said, keys at least have a sensible, non-generic name in an application, like `category`, `name`, `chipset_id` or whatever. But when you create a generic helper method that accepts any hash, then using those `k, v` is just fine: they are as specific as they can, and while they _could_ be in that respect written as `|key, value|` most people would find that unnecessary, as it's idiomatic like `i` and `j` with two-dimensional loops (though the same applies here; often those indices have more semantics than just an index, and unless the method is generic, it's better to use those names)
