### ISSUE TITLE
Single quotes vs double quotes

### ISSUE THREAD

**Issue by joelmccracken** [rubocop-hq/ruby-style-guide#184]
This style guide sparked a large discussion on the ruby rogues parley mailing list about, of all things, the single vs double quotes preference, with much of the community divided, but seemingly more in favor of double quotes everywhere.

I'm not really sure this is an issue, so whatever, close it if you want to. I guess that it might be worth discussing though.

**Comment by juanibiapina** [comment]
A year later: http://anti-pattern.com/always-use-double-quoted-strings-in-ruby

Are you ready to continue evolving this? Double quotes should at least be "the first option", if not the only one.

**Comment by bbatsov** [comment]
Don't really care about those blog posts. I can write a few of them myself, extolling the virtues of this semantic rule. I've made it configurable, I respect the opinions of others, but this will never be the default.

**Comment by midwire** [comment]
I agree with @bbatsov about the blog posts. They are like defecation, everyone does it and you can find an article or post to support almost ANY position on ANY topic. If not, you can write your own.

To the point: Personally, I could be ambivalent about this issue. However, if intent matters (which it should) then single should be used for all strings where I don't *intend* for interpolation to occur. Larry Wall's 3 virtues aside, the laziness of just punting to always use double-quotes seems... well, lazy yes, but also just sloppy, IMO. e.g. "I don't want to have to think about the intent of each string so I'll just double quote everything." Should we get rid of `.freeze` as well because I may want to modify a string and I just don't want to have to think about it?

We have single-quoted strings in Ruby for a reason. Code to show intent.

**Comment by juanibiapina** [comment]
You can't agree with @bbatsov because he provided no arguments. In fact, he has provided hilarious arguments for a community guide on this thread: https://github.com/bbatsov/rubocop/issues/1615

1. "I don't really want to change it"
2. "The reason why this is the default has nothing to do with performance"
3. "I didn't care back then and I don't care now. I ask people to respect my wishes and just let this matter go."

**Comment by midwire** [comment]
Seriously? I can't agree with @bbatsov? I wasn't aware of that regulation. I suppose, then, my previous agreement is null and void.

Please @juanibiapina, read my post again:

> I agree with @bbatsov about the **_blog posts_**. They are like defecation, everyone does it and you can find an article or post to support almost ANY position on ANY topic. If not, you can write your own.

In fact, you make my point perfectly. You are pooping out your opinion that I can't agree with something; which opinion is 1) false (indeed I can agree with any statement made by anyone) and 2) entirely subjective.

Like you, all that I was attempting to do is make my tiny voice heard regarding this issue. How very democratic of you to try and shoot it down.

**Comment by joelmccracken** [comment]
This is whole thing is useless; the value of one style over the other is nearly negligible. @bbatsov already added a note in the style guide. Lets stop arguing about this and go write code!

In that spirit, I'm unsubscribing from this thread.

**Comment by midwire** [comment]
Opinions are useless. I'm out as well, but before I go, good on you @bbatsov for sticking to your guns in the face of the mob.

**Comment by juanibiapina** [comment]
@midwire I didn't mean to attack you. It was a phrase badly constructed because English is not my native tongue. My sincere appologies.

A better phrasing would be: @bbatsov can't be agreed with, because he has not provided arguments.

But that statement would be invalid anyway, since you're talking about the posts and not the quotes problem.
