### ISSUE TITLE
Conventions for %w, %W, %q, %Q, etc.

### ISSUE THREAD

**Issue by mitio** [rubocop-hq/ruby-style-guide#29]
I think this guide is turning into something great.

As many people have already seen it and probably even more will, it has the potential to become a bit more official than it wants to be :) Along these lines, I think it will be a good idea to include convention hints for some of the rarely-used constructs.

Thus, it is my opinion that adding some info on the `%`-notion (e.g. `%w`, `%W`, `%q`, `%Q`, `%r`, `%{...}`, etc) won't be a bad idea. I, personally, haven't seen anything consistent on the subject out there.

Also it should be noted that these constructs must be avoided unless they're really needed in the particular situation.

What do you guys think?

**Comment by jibiel** [comment]
Sorry for the gravedigging, but what's your opinion on contexts like this one:

```ruby
add_index :thingies, [:category_id, :property], unique: true
add_index :thingies, %i{category_id property}, unique: true
```

I think the second example loses in readability and this is obvious exception to the rule, since code like this rarely changes and [the provided examples](https://github.com/bbatsov/ruby-style-guide#percent-w) (`types` / `states` / `roles`) show only one side of the coin: ease of adding/removing items.
