### ISSUE TITLE
Adding tap method usage

### ISSUE THREAD

**Issue by abishekaditya** [rubocop-hq/ruby-style-guide#613]
[Object#tap](http://apidock.com/ruby/Object/tap) is very useful in rare situations and makes code more readable. Can we add a section related to guidlines ragarding good usage of tap method? I can create a pull request if someone can guide me

**Comment by bbatsov** [comment]
What kinds of usages do you have in mind?

**Comment by abishekaditya** [comment]
1. The obvious one being debugging and checking where something goes wrong
 ```ruby
arr.map { |i| i**2 }.tap {|n| p n}.reverse
```

2. clarity
```ruby
user = User.new.tap do |u|
   u.username = "foobar"
  u.save!
```

3.  object manipulation during return in a single line
```ruby
def method_name
  ...
  object_name.tap(&:serialize)
end
```

and some more exotic use cases. A guideline will help in making sure its use is in check.

**Comment by sadhu89** [comment]
I agree a section about `tap` would be useful. Specially about overusing. 
I like this extract from the Platafomatec Ruby guidelines (http://guidelines.plataformatec.com.br/ruby.html):

- Avoid Object#tap when it does not lead to more concise code. In the following case, it seems unnecessary and compromises readability. By using variable the returning value is clearer.

```ruby
# Instead of this...
article.save.tap do |saved|
  do_something if saved
end

# ...you should do this.
saved = article.save
do_something if saved
saved
```

**Comment by bbatsov** [comment]
> I agree a section about tap would be useful. Specially about overusing.

Fine by me.

**Comment by marcandre** [comment]
Came here because I was surprised we don't have a cop against this yet when [reading this code](https://github.com/rubocop-hq/rubocop/blob/3ef92bbbc69b8b6cbe75485067c8addf75a948d6/lib/rubocop/config.rb#L37) which I believe is a bad usage of `tap`.

@abishekaditya wrote:

>     1. clarity
> 
> 
> ```ruby
> user = User.new.tap do |u|
>    u.username = "foobar"
>    u.save!
> end
> ```

That is an example of when *not* to use it.
Isn't this simpler, easier to reader and more performant?

```ruby
user = User.new
user.username = "foobar"
user.save!
user
```

>     1. object manipulation during return in a single line
> 
> 
> ```ruby
> def method_name
>   ...
>   object_name.tap(&:serialize)
> end
> ```

What does `serialize`? If it mutates the receiver, it should return it too making `tap` useless. If it doesn't, then it's a strange API.

>     1. The obvious one being debugging and checking where something goes wrong
> 
> 
> ```ruby
> arr.map { |i| i**2 }.tap {|n| p n}.reverse
> ```

This is the best and imo only good usage of `tap`.

As such the rule should be, imo: do not use `tap` except for debugging purposes.
