### ISSUE TITLE
Discussion: parameter alignment (no-double-indent)

### ISSUE THREAD

**Issue by rstacruz** [rubocop-hq/ruby-style-guide#619]
What's the rationale behind the `no-double-indent` rule?

> Align the parameters of a method call if they span more than one line. When aligning parameters is not appropriate due to line-length constraints, single indent for the lines after the first is also acceptable.
> —[#no-double-indent](https://github.com/bbatsov/ruby-style-guide#no-double-indent)

This rule usually makes for some very strange indentation:

```rb
# OK
Rails.application.middleware.use Rack::HostRedirect,
                                 target: '/',
                                 timeout: 3600,
                                 use_ssl: true
```

The alternative is more reasonable, but produces strange lonely `)` lines:

```rb
# OK
Rails.application.middleware.use(
  Rack::HostRedirect,
  target: '/',
  timeout: 3600,
  use_ssl: true
)
```

What seems natural is to let parameters be indented by two spaces, but this isn't allowed.

```rb
# ✗ Not allowed
Rails.application.middleware.use Rack::HostRedirect,
  target: '/',
  timeout: 3600,
  use_ssl: true
```

---

*(Disclaimer: the example is entirely fictional, but I've seen many code like it in the wild)*

**Comment by bbatsov** [comment]
Apart from the fact the the community strongly favours the styles outlined in the guide (an observation based on Ruby code you'd find in the wild), I think what you suggest never became popular because it creates a bit of the disconnect between the args on the first line and those that follow them. I don't think that's something Ruby-specific, though. Similar indentation patterns were established in many languages.

I see no one else commented on this ticket, so I guess it's safe to close it.
