### ISSUE TITLE
No spaces before curly braces `{`

### ISSUE THREAD

**Issue by khiav223577** [rubocop-hq/ruby-style-guide#654]
I wonder why some developers write spaces before `curly braces`, but nonetheless do not write spaces before `round braces` and `square braces`? And why it is bad to have no spaces?
EX: 

```rb
calc(val)
hash[idx]
calc { ... }
```
instead of 
```rb
calc(val)
hash[idx]
calc{ ... }
```
or
```rb
calc (val)
hash [idx]
calc { ... }
```
I feel it is more consistent to have no spaces before not only round and square braces but also curly braces. A space before curly braces make me think it is a method-call without the round brace and take a hash as parameter at first glance.
```rb
call_method val
call_method { ... }
```

**Comment by bbatsov** [comment]
I think the simple answer would be - because the `{}` counterparts for blocks `do` and `end` force you to have a space. Not to mention that the current arrangement is a time-honoured Ruby convention that's too entrenched to ever be changed. 

> A space before curly braces make me think it is a method-call without the round brace and take a hash as parameter at first glance.

Well, the context should immediately make it obvious what you're actually dealing with.
