### ISSUE TITLE
Recommend using allowlist/denylist instead of whitelist/blacklist

### ISSUE THREAD

**Issue by bai** [rubocop-hq/ruby-style-guide#820]
👋🏽 My apologies if this topic has been already brought up and I missed it.

Many projects across the aisle, including but not limited to [Chromium](https://chromium.googlesource.com/chromium/src/+/master/styleguide/inclusive_code.md#racially-neutral) ([see also](https://bugs.chromium.org/p/chromium/issues/detail?id=842296)) and [osquery](https://github.com/osquery/osquery/issues/6475), are moving away from whitelist/blacklist terminology.

Thoughts on adding a rule that'd suggest using `allowlist`/`denylist` instead? (Alternatively, we could suggest against using those terms without offering a replacement.)

**Comment by blacklistisnotracist** [comment]
I do agree allowlist/denylist may be better terms because they are more descriptive. That being said, calling blacklist or whitelist a racist word is simply wrong.

First, blacklist's origins have nothing to do with black people. What's more, it has never been used as an abusive word against black people. It's only a certain group of extreme non-black liberals who find the word offensive and try to make them look like it has racist connotations. It's as ridiculous as people who think wearing Chinese clothes is offensive for Chinese people unless they are worn by Chinese people.

Black, as a color, carries negative connotations across many cultures. It's so embedded that hunting down every word from every language is almost impossible and meaningless.

Let's stop calling a group of people black first. Let's start from there. Color comes first, race came later. Colors are tied to images, which can't be changed.

Let's stop the hypocrisy and focus on something that have real impacts.

**Comment by bbatsov** [comment]
RuboCop moved away from blacklist/whitelist a while ago as well - see https://github.com/rubocop-hq/rubocop/commit/832355037096173703d2e6d5eb0983a78c4e5c67 As you can see we opted for way more descriptive names than allowlist and denylist, which are too generic, just as the terms they are replacing.

**Comment by blacklistisnotracist** [comment]
@bbatsov I'm not opposing the change. Sorry for my rants on which came from some other discussions where people want to associate these words with racism. Reading the desc of the original issue, it's not mentioned so plz nvm.

**Comment by pirj** [comment]
I believe the scope of this guide doesn't reach ethical, moral, and politeness areas.

There should probably be some cross-language guide that would postulate those guidelines. I'll be happy to introduce it for the reference of open-source projects I'm working on.

If you happen to stumble across such a guide or happen to find time to start writing one, please reach out!
