### ISSUE TITLE
Strongly disagree with single quote rule

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/ruby-style-guide#96]
You state:

"Prefer single-quoted strings when you don't need string interpolation or special symbols such as \t, \n, ', etc."

I disagree with that.

1) This is not a convention widely followed. For example I'd say that you will find more double quoted simple strings in Rails than single quoted ones (if you exclude `requires` which are typically single quoted).

2) It's a rule I personally dislike because I usually do not know if a string will ever require a special character or interpolation (again except for `require`s). Example:

```
raise ArgumentError, 'Expected a string'
```

could later become:

```
raise ArgumentError, "Expected a string, got #{some_arg}"
```

I dislike having to change single quotes to double quotes.

3) I don't think there is much to gain with such a rule. If there was to be a rule, then I'd say prefer single-quoted strings for strings that should not have special characters nor interpolation (like files to require), but for everything else, I think it should be a personal choice as many policies, e.g. double quote only when needed, or on the contrary single quote only when needed (my preference), both make sense.

**Comment by JikkuJose** [comment]
@marcandre it [doesn't seem worth it](http://viget.com/extend/just-use-double-quoted-ruby-strings).

**Comment by marcandre** [comment]
@JikkuJose Thinking it might be about performance is plain wrong for at least two reasons. Please read [this info about the performance aspect](https://stackoverflow.com/questions/1836467/is-there-a-performance-gain-in-using-single-quotes-vs-double-quotes-in-ruby#answer-1836838)

**Comment by JikkuJose** [comment]
@marcandre I didn't really get it. Quite a newbie to Ruby; So let me clarify: Is this to maintain consistent style? If so, why not use double quotes everywhere and find consistency like that?

In short does this just boil down to personal taste? and being consistent with rather large part of the community?

**Comment by onebree** [comment]
@JikkuJose As mentioned, take the phrase `Hello, world!`. With single quotes process much faster than double quotes. When you write a Ruby program with speed in mind, remember this. Otherwise, it is mostly personal taste. I use mainly double quotes, but will decide if that (noticeably) affects my test speeds. (I doubt it, with integration testing.)

And yes, consistency is the thing to take away from the guide. While it is a community guide, I have seen individuals/companies fork this project and tailor it to their needs.

**Comment by marcandre** [comment]
>  With single quotes process much faster than double quotes

?? what ??

**Comment by onebree** [comment]
@marcandre I think faster than I type. I edited my comment

**Comment by marcandre** [comment]
My comment stays the same

**Comment by JikkuJose** [comment]
@onebree it seems there isn't any significant performance advantages for this choice!

**Comment by onebree** [comment]
I do not have them on hand, but I have seen benchmarks showing that single-quotes process faster than double quotes. It may not be a large difference, but one nonetheless

**Comment by marcandre** [comment]
@onebree Sorry to repeat myself, but [please read this](https://stackoverflow.com/questions/1836467/is-there-a-performance-gain-in-using-single-quotes-vs-double-quotes-in-ruby#answer-1836838), and don't repeat stuff you don't understand and without references, as it will often be wrong (like in this case).

**Comment by jdickey** [comment]
Over three years later and we *still* can't let this go. Some excessively masochistic PhD student will successfully defend a dissertation mocking the hell out of benchmarking fetishes, with this discussion (and @marcandre's [SO answer](https://stackoverflow.com/questions/1836467/is-there-a-performance-gain-in-using-single-quotes-vs-double-quotes-in-ruby#answer-1836838)) as highlighted sources.

**Comment by onebree** [comment]
Just to clarify, I am not obsessed with benchmarks, but they do serve their purpose at times. I mainly use double-quotes, while a coworker uses mainly single-quotes. I think, if possible, we should burn this issue, since the guide includes both options.

**Comment by JikkuJose** [comment]
Must have become sort of habit an d personal preference for many to just burn the issue. Personally, I don't see why someone should consider single quotes.

Anyways, thanks for your time.

**Comment by maicher** [comment]
@JikkuJose By saying:
> Personally, I don't see why someone should consider single quotes.

you showed a lack of understanding to:
>I like it visually and it's slightly more explicit, since there's no need to parse the string to see if it contains any expression.'

**Comment by JikkuJose** [comment]
@maicher oh was it so? Then I am sorry to hurt feelings, I just meant the argument seemed just as an arbitrary choice. And I feel seeking consistency in using double quotes everywhere feels like a better choice.

**Comment by bbatsov** [comment]
If I hear one more time the argument about performance... This was never about performance, it's a semantic rule and its benefit is obviously that more information is conveyed by the choice of the literal. There's really no right or wrong choice, there's no better choice, etc. I wish people would realize this someday, instead of wasting of ton of time bikeshedding and arguing over trivial details.

**Comment by onebree** [comment]
@bbatsov can we close this, or lock the commenting?

**Comment by marcandre** [comment]
@onebree It has been closed for over 3 years. Anyone can click on 'unsubscribe' to not get notifications.

**Comment by JikkuJose** [comment]
Sorry to have brought it up. Thanks for your time anyways.

**Comment by roberts1000** [comment]
@bbatsov There's really no right or wrong choice, there's no better choice, etc.

This is exactly why it should not be part of the style guide.  There's no community accepted preference, no performance benefit one way or the other, and no clear readability benefit/preference.  The time it takes to enforce this rule in a code base and pay software engineers to deal with is a complete waste.  I disable the check in our .rubyocop.yml on every project and let my developers do whatever they want with their strings.

**Comment by krtschmr** [comment]
i got 9000 violations. 97% are double quotes used. 

i won't change that.

**Comment by ls-machvee** [comment]
The decision to use one type of quote over the other occurs constantly in code editing.    With double quotes as a standard, that decision-making is dramatically reduced.    It's not a *style* issue like indentation width or indent character because both are equal treated by the interpreter.   When I open a double-quote, I can choose to add an interpolation, not interpolate, include a special char sequence, or simple type characters.

**Comment by ramonrails** [comment]
I did some benchmarking on ruby 3.3.0 YJIT

```➜ ruby -v --yjit
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) +YJIT [x86_64-darwin23]
```
Using [`Benchmark.bmbm`](https://rubyapi.org/3.2/o/benchmark#method-c-bmbm). Why?

Sometimes benchmark results are skewed because code executed earlier encounters different garbage collection overheads than that run later. `bmbm` attempts to minimize this effect by running the tests twice, the first time as a rehearsal in order to get the runtime environment stable, the second time for real. `GC.start` is executed before the start of each of the real timings; the cost of this is not included in the timings. In reality, though, there’s only so much that `bmbm` can do, and the results are not guaranteed to be isolated from garbage collection and other effects.


100k times (string literals in memory of small apps or low traffic?)
```
irb(main):005* Benchmark.bmbm do |x|
irb(main):006*   x.report("double_quotes") { 1_00_000.times { "the quick brown fox jumps right over the lazy little dogs" }}
irb(main):007*   x.report("single_quotes") { 1_00_000.times { 'the quick brown fox jumps right over the lazy little dogs' }}
irb(main):008*   x.report("double_quotes frozen") { 1_00_000.times { "the quick brown fox jumps right over the lazy little dogs".freeze }}
irb(main):009*   x.report("string_quotes frozen") { 1_00_000.times { 'the quick brown fox jumps right over the lazy little dogs'.freeze }}
irb(main):010> end
Rehearsal --------------------------------------------------------
double_quotes          0.014653   0.000180   0.014833 (  0.014833)
single_quotes          0.012735   0.000108   0.012843 (  0.012843)
double_quotes frozen   0.003047   0.000001   0.003048 (  0.003046)
string_quotes frozen   0.003239   0.000006   0.003245 (  0.003257)
----------------------------------------------- total: 0.033969sec

                           user     system      total        real
double_quotes          0.016255   0.000121   0.016376 (  0.016373)
single_quotes          0.013331   0.000109   0.013440 (  0.013439)
double_quotes frozen   0.003664   0.000001   0.003665 (  0.003663)
string_quotes frozen   0.003641   0.000001   0.003642 (  0.003640)
```

A million times (string literals in memory of large apps or high volume traffic?)
```
irb(main):059* Benchmark.bmbm do |x|
irb(main):060*   x.report("double_quotes") { 1_000_000.times { "the quick brown fox jumps right over the lazy little dogs" }}
irb(main):061*   x.report("single_quotes") { 1_000_000.times { 'the quick brown fox jumps right over the lazy little dogs' }}
irb(main):062*   x.report("double_quotes frozen") { 1_000_000.times { "the quick brown fox jumps right over the lazy little dogs".freeze }}
irb(main):063*   x.report("string_quotes frozen") { 1_000_000.times { 'the quick brown fox jumps right over the lazy little dogs'.freeze }}
irb(main):064> end
Rehearsal --------------------------------------------------------
double_quotes          0.145729   0.001655   0.147384 (  0.147418)
single_quotes          0.124142   0.001011   0.125153 (  0.125171)
double_quotes frozen   0.030274   0.000005   0.030279 (  0.030279)
string_quotes frozen   0.032117   0.000009   0.032126 (  0.032130)
----------------------------------------------- total: 0.334942sec

                           user     system      total        real
double_quotes          0.133897   0.001080   0.134977 (  0.135103)
single_quotes          0.135984   0.001131   0.137115 (  0.137186)
double_quotes frozen   0.030961   0.000005   0.030966 (  0.030964)
string_quotes frozen   0.031595   0.000009   0.031604 (  0.031607)
```

As you can see, the double-quotes are in fact faster than single-quotes. This defies my assumption so far about ruby string literals.

My conclusion:

- I will stop worrying about double quotes or single
- Just freeze them for better performance
- I will configure rubocop/standard settings to ignore making suggestions about single-quotes
