### ISSUE TITLE
`self.` is often not needed and therefore better left off.

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/ruby-style-guide#97]
Especially for developers coming from Javascript, I'd suggest stating that the `self.` in `self.my_method` is usually not needed and should be left off for brevity's sake.

I'll write something up if you'd like me to.

**Comment by dsferreira** [comment]
My thoughts on this matter:

I believe public interface should be self contained.
To emphasise this I like to enforce self in public methods inside their classes or modules so that their usage is conscious enough.
This way the developer is forced to pay for the cost of an extra method exposed in the public interface.
Code readability is also improved by showing to the reader the nature of each one of the methods in use.
